[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "myxo"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "tqdm",
    "pandas",
    "scipy",
    "matplotlib",
    "numexpr",
    "numpy",
    "h5py",
    "toolbox @ git+https://github.com/matevosashot/toolbox.git"
]

[tool.setuptools]
packages = ["myxo"]

[tool.setuptools.package-dir]
"myxo" = "src"
